title: "جبر خطی عددی"
description: "دوره دانشگاهی Numerical Linear Algebra (به زبان فارسی)"
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
logo: /assets/images/logo.png
show_downloads: false
markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM
